config/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('news/', include('news.urls', namespace='news')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import index, contacts

urlpatterns = [
    path('', index),
    path('contacts/', contacts)
]

news/urls.py
from django.urls import path
from news.views import NewsCreateView, NewsListView, NewsDetailView, NewsUpdateView, NewsDeleteView
from news.apps import NewsConfig

app_name = NewsConfig.name

urlpatterns = [
    path('',NewsListView.as_view(), name='list'),
    path('create/', NewsCreateView.as_view(), name='create'),
    path('view/<int:pk>/', NewsDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', NewsUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', NewsDeleteView.as_view(), name='delete'),
]

news/models.py
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(
        max_length=150, verbose_name='slug',  null=True, blank=True)
    text = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(verbose_name='Превью', null=True, blank=True)
    data_created = models.DateTimeField(
        verbose_name='Дата создания', auto_now_add=True)
    is_published = models.BooleanField(
        verbose_name='Опубликовано', default=True)
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'

news/views.py
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify
from django.contrib.auth.mixins import LoginRequiredMixin
from news.models import News


class NewsCreateView(LoginRequiredMixin, CreateView):
    model = News
    fields = ('title', 'text', 'image', 'is_published')
    success_url = reverse_lazy('news:list')

    def form_valid(self, form):
        if form.is_valid():
            new_news = form.save()
            new_news.slug = slugify(new_news.title)
            new_news.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Добавление новости'
        return context_data

    def get_success_url(self):
        return reverse('news:list')


class NewsListView(ListView):
    model = News

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Новости'
        return context_data

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True).order_by('-data_created')
        return queryset


class NewsDetailView(DetailView):
    """Контроллер просмотра отдельной новости"""
    model = News

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.object.title
        return context_data

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class NewsUpdateView(LoginRequiredMixin, UpdateView):
    model = News
    fields = ('title', 'text', 'image', 'is_published')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Редактирование новости'
        return context_data

    def form_valid(self, form):
        if form.is_valid():
            new_news = form.save()
            new_news.slug = slugify(new_news.title)
            new_news.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('news:view', args=[self.kwargs.get('pk')])


class NewsDeleteView(LoginRequiredMixin, DeleteView):
    model = News
    success_url = reverse_lazy('news:list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Удаление новости'
        return context_data

news/templates/news/news_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        Удаление новости
    </h1>
</div>

<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить "{{object.title}}"?</p>
                    <button type="submit" class="btn btn-danger">
                        Подтвердить
                    </button>
                    <a href="{% url 'news:list' %}" class="btn btn-primary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

news/templates/news/news_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}


{% block content %}

<div class="col-12 px-3 py-3 pt-md-5 pb-md-4 mx-auto">
	{% if object.image %}
	<div class="row text-start">
		<img style='height: 100%; width: 100%; object-fit: contain' src="{{ object.image|mediapath }}" />
	</div>
	{% endif %}
	<div class="card mb-4 box-shadow">
		<div class="card-header">
			<h3 class="card-title">
				{{ object.title }}
			</h3>
		</div>
		<div class="card-body">
			<p>
				{{ object.text|linebreaksbr }}
			</p>
			<p>
				Создано: {{ object.data_created }}
			</p>
			<div class="d-flex justify-content-between align-items-center">
				<div class="btn-group">
					<a href="{% url 'news:edit' object.pk %}" class="btn btn-sm btn-outline-primary">Edit</a>
					<a href="{% url 'news:delete' object.pk %}" class="btn btn-sm btn-outline-danger">Delete</a>
				</div>
			</div>
		</div>
		<div class="card-footer">
			Просмотры: {{ object.views_count }}
		</div>
	</div>
</div>
{% endblock %}

news/templates/news/news_form.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        {% if object %}
        Редактирование "{{ object.title }}"
        {% else %}
        Добавление новости
        {% endif %}
    </h1>
</div>

<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

news/templates/news/news_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<h1 class="display-4">Новости</h1>
</div>

<div class="container">
	{% if user.is_staff %}
	<a class="btn btn-outline-primary mb-4" href="{% url 'news:create' %}">Добавить новость</a>
	{% endif %}
	<div class="row row-cols-1  row-cols-md-2 g-4 text-center">
		{% for object in object_list %}
		<div class="col-lg-6 col-md-12">
			<div class="card h-100">
				<div class="card-body">
					<h3 class="card-title pricing-card-title">{{ object }}</h3>
					<ul class="list-unstyled mt-3 mb-4 text-start m-3">
						<p>{{ object.text|linebreaksbr }}</p>
					</ul>
				</div>
				<div class="p-3">
					<a href="{% url 'news:view' object.pk %}" type="button"
						class="btn btn-lg btn-block stretched-link btn-outline-dark">Подробнее</a>
				</div>
				<div class="card-footer">
					Просмотры: {{ object.views_count }}
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>

{% endblock %}