config/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('news/', include('news.urls', namespace='news')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import index, contacts

urlpatterns = [
    path('', index),
    path('contacts/', contacts)
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserDetailView, UserUpdateView, EmailConfirmationSentView, \
    UserConfirmEmailView, EmailConfirmedView, EmailConfirmationFailedView, PasswordRecoveryView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserDetailView.as_view(), name='profile'),
    path('profile/edit/', UserUpdateView.as_view(), name='profile_edit'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('password_recovery/', PasswordRecoveryView.as_view(), name='password_recovery'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django_countries.fields import CountryField


NULLABLE = {'null': True, 'blank': True}

# Create your models here.


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')
    phone = models.CharField(
        max_length=35, verbose_name='Номер телефона', **NULLABLE)
    country = CountryField(blank_label="(выберите страну)", **NULLABLE)
    avatar = models.ImageField(
        upload_to='users', verbose_name='аватар', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm, PasswordResetForm
from django import forms
from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

    def clean_email(self):
        """
        Проверка email на уникальность
        """
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Такой email уже используется в системе')
        return email


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'country', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        phone_number = self.fields['phone'].widget

        self.fields['password'].widget = forms.HiddenInput()
        phone_number.attrs['class'] = "form-control bfh-phone"
        phone_number.attrs['data-format'] = "+7 (ddd) ddd-dd-dd"
        phone_number.attrs['value'] = "9999999999"


class PasswordRecoveryForm(forms.Form):
    email = forms.EmailField(label='Email')

users/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView

from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.crypto import get_random_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views import View
from django.views.generic import CreateView, DetailView, UpdateView, TemplateView, FormView

from config import settings
from users.forms import UserRegisterForm, UserForm, PasswordRecoveryForm
from users.models import User
from services.mixins import UserIsNotAuthenticated


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(UserIsNotAuthenticated, CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация на сайте'
        return context

    # def form_valid(self, form):
    #     new_user = form.save()
    #     send_mail(
    #         subject='Подтверждение почты',
    #         message='123',
    #         from_email=settings.EMAIL_HOST_USER,
    #         recipient_list=[new_user.email]
    #     )
    #     return super().form_valid(form)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        # Функционал для отправки письма и генерации токена
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={
                                      'uidb64': uid, 'token': token})
        current_site = Site.objects.get_current().domain
        send_mail(
            'Softy: Подтвердите свой электронный адрес, перейдя по ссылке',
            f'Пожалуйста, перейдите по следующей ссылке, чтобы подтвердить свой адрес электронной почты: http://{current_site}{activation_url}',
            settings.EMAIL_HOST_USER,
            [user.email],
            fail_silently=False,
        )
        print(f'Email sent {user.email}')
        return redirect('users:email_confirmation_sent')


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User

    def get_object(self, queryset=None):
        return self.request.user


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


class UserConfirmEmailView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('users:email_confirmed')
        else:
            return redirect('users:email_confirmation_failed')


class EmailConfirmationSentView(TemplateView):
    template_name = 'users/email_confirmation_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо активации отправлено'
        return context


class EmailConfirmedView(TemplateView):
    template_name = 'users/email_confirmed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес активирован'
        return context


class EmailConfirmationFailedView(TemplateView):
    template_name = 'users/email_confirmation_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес не активирован'
        return context


class PasswordRecoveryView(FormView):
    template_name = 'users/password_recovery.html'
    form_class = PasswordRecoveryForm
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        user = User.objects.get(email=email)
        length = 12
        alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
        password = get_random_string(length, alphabet)
        user.set_password(password)
        user.save()
        subject = 'Password Recovery'
        message = f'Your new password: {password}'
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
            fail_silently=False,
        )
        return super().form_valid(form)

users/templates/users/email_confirmation_failed.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4"></h1>
    </div>
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Ошибка подтверждения по электронной почте</h4>
        <p>Ссылка для подтверждения по электронной почте недействительна или срок ее действия истек. Пожалуйста,
            зарегистрируйтесь снова.</p>
    </div>
{% endblock %}

users/templates/users/email_confirmation_sent.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4"></h1>
    </div>
    <div class="alert alert-info" role="alert">
        <h4 class="alert-heading">Письмо подтверждения отправлено!</h4>
        <p>
            На ваш адрес электронной почты было отправлено письмо с подтверждением. Пожалуйста, проверьте свою
            электронную почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.
            Если письмо не пришло, проверьте папку спам.
        </p>
    </div>
{% endblock %}

users/templates/users/email_confirmed.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4"></h1>
    </div>
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Электронная почта подтверждена</h4>
        <p>Ваш адрес электронной почты успешно подтвержден. Спасибо за регистрацию!</p>
    </div>

{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Авторизация</h1>
    </div>
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        <div class="d-grid gap-2 col-8 mx-auto">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="d-grid gap-2 col-4 mx-auto">
                            <button type="submit" class="btn btn-outline-dark">Войти</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <a href="{% url 'users:password_recovery' %}">Забыли пароль?</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Регистрация</h1>
    </div>
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post" action="{% url 'users:register' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-grid gap-2 col-6 mx-auto">
                            <button type="submit" class="btn btn-outline-dark">Зарегистрироваться</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<h1 class="display-4">Профиль</h1>
</div>
<div class="row">
	<div class="col-2"></div>
	<div class="col-8">
		<div class="card">
			<div class="card-header"></div>
			<div class="card-body">
				<div class="col-8">
					<p><strong>Почта:</strong> {{ object.email }}</p>
					<p><strong>Имя:</strong> {{ object.first_name }}</p>
					<p><strong>Фамилия:</strong> {{ object.last_name }}</p>
					<p><strong>Страна:</strong> <span class="bfh-countries" data-country="{{ object.country }}"
							data-flags="true"></span></p>
					<p><strong>Phone:</strong> {{ object.phone }}</p>
				</div>
				<div class="col-4">
					{#object.avatar#}
				</div>
			</div>
		</div>
		<div class="card-footer justify-content-end">
			<a class="btn btn-outline-dark" href="{% url 'users:profile_edit' %}">Редактировать</a>
		</div>
	</div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<h1 class="display-4">Редактирование профиля</h1>
</div>
<div class="row">
	<div class="col-3"></div>
	<div class="col-6">
		<div class="card">
			<div class="card-header"></div>
			<form method="post" enctype="multipart/form-data">
				<div class="card-body">
					{% csrf_token %}
					{{ form.as_p }}
				</div>
				<div class="card-footer">
					<button type="submit" class="btn btn-success">Сохранить</button>
					<button type="button" class="btn btn-danger" href="{% url 'users:profile' %}">Отмена</button>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}