catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import AddToCartView, CartView, IndexView, ContactsView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, RemoveFromCartView, public_product, CategoryListView, CategoryDetailView, CategoryCreateView
from catalog.apps import MainConfig

app_name = MainConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('view/<int:pk>/', cache_page(60)
         (ProductDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('create/', ProductCreateView.as_view(), name='create'),

    path('category/', CategoryListView.as_view(), name='category'),
    path('category/create', CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/', CategoryDetailView.as_view(),
         name='category_products'),

    path('cart/', CartView.as_view(), name='view_cart'),
    path('add_to_cart/<int:pk>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove_from_cart/<int:pk>/',
         RemoveFromCartView.as_view(), name='remove_from_cart'),

    path('public_product/<int:pk>/', public_product, name='public_product')
]

config/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('news/', include('news.urls', namespace='news')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import index, contacts

urlpatterns = [
    path('', index),
    path('contacts/', contacts)
]

catalog/models.py
from django.utils import timezone
from django.db import models
from django import forms

from users.models import User

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Категория')
    description = models.CharField(
        max_length=500, verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name='Категория')
    image = models.ImageField(upload_to='products/',
                              verbose_name='Изображение', **NULLABLE)
    is_published = models.BooleanField(
        default=False, verbose_name='Опубликовано')
    price = models.PositiveIntegerField(verbose_name='Цена')
    data_created = models.DateField(
        verbose_name='Дата создания', auto_now_add=True)
    data_changed = models.DateField(
        verbose_name='Дата последнего изменения', auto_now=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        permissions = [
            (
                "set_published",
                "Can publish post"
            )
        ]


class CartItem(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name='Продукт')
    quantity = models.PositiveIntegerField(
        default=0, verbose_name="Количество")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Покупатель")
    date_added = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата добавления")

    class Meta:
        verbose_name = 'корзина'
        verbose_name_plural = 'корзины'


class Version(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name='продукт')
    title = models.CharField(max_length=150, verbose_name='Наименование')
    number_version = models.IntegerField(
        primary_key=True, verbose_name='Номер версии')
    is_active = models.BooleanField(
        verbose_name='активная версия', default=False)

    def save(self, *args, **kwargs):
        if self.is_active:  # Если эта версия должна быть активной
            versions_set = Version.objects.filter(
                product=self.product)  # Получаем все версии продукта
            for vers in versions_set:
                vers.is_active = False  # Делаем все версии неактивными
                vers.save()  # Сохраняем изменения
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Версия продукта'
        verbose_name_plural = 'Версии продукта'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_active':
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        exclude = ['data_changed', 'data_created', 'owner', 'is_published']

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        excludes = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        if cleaned_data in excludes:
            raise forms.ValidationError('Указаны запрещенные слова в названии')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        excludes = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        if cleaned_data in excludes:
            raise forms.ValidationError('Указаны запрещенные слова в названии')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        exclude = ['product']


class ModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'category']

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        excludes = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        if cleaned_data in excludes:
            raise forms.ValidationError('Указаны запрещенные слова в названии')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        excludes = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        if cleaned_data in excludes:
            raise forms.ValidationError('Указаны запрещенные слова в названии')

        return cleaned_data

catalog/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render, redirect

from catalog.forms import ProductForm, VersionForm, ModeratorForm
from catalog.models import Product, Version, Category, CartItem
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, DeleteView, ListView
from django.urls import reverse_lazy, reverse

from catalog.services import category_list_cache


class IndexView(TemplateView):
    """Контроллер просмотра домашней страницы"""
    template_name = 'catalog/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Product.objects.all()
        context_data['title'] = 'Главная'
        return context_data


class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Контакты'
        return context_data

    def post(self, request):
        if request.method == 'POST':
            name = request.POST.get('name')
            phone = request.POST.get('phone')
            email = request.POST.get('email')
            text = request.POST.get('message')
        print(
            f'You have new message from {name}({phone}, email:{email}): {text}')
        return render(request, 'catalog/contacts.html', self.extra_context)


class ProductDetailView(DetailView):
    """Контроллер просмотра отдельного продукта"""
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.object.name
        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Добавление продукта'
        return context_data

    def get_success_url(self):
        messages.success(self.request, 'Отправлено на проверку модерации')
        return reverse('catalog:index')

    def form_valid(self, form):
        new_product = form.save()
        new_product.owner = self.request.user
        new_product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if self.object.owner != self.request.user and not user.is_superuser and not user.groups.filter(pk=1):
            raise Http404
        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(
            Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(
                self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        if self.request.user.groups.filter(pk=1):
            context_data['moderform'] = ModeratorForm(
                self.request.POST, instance=self.object)
        context_data['title'] = 'Редактирование продукта'
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:edit', args=[self.kwargs.get('pk')])


@permission_required("users.set_published")
def public_product(request, pk):
    product = Product.objects.get(pk=pk)
    product.is_published = {product.is_published: False,
                            not product.is_published: True}[True]
    product.save()
    return redirect(reverse('catalog:index'))


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Удаление продукта'
        return context_data

    def get_object(self, queryset=None):
        product = super(ProductDeleteView, self).get_object()
        if not product.owner == self.request.user and not self.request.user.is_superuser:
            raise Http404
        return product


class CategoryListView(ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = category_list_cache()
        context_data['title'] = 'Категории'
        return context_data


class CategoryDetailView(DetailView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Product.objects.filter(
            category=self.object)
        context_data['title'] = self.object.name
        return context_data


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    fields = ['name', 'description']

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Добавление категории'
        return context_data

    def get_success_url(self):
        return reverse('catalog:category')


class CartView(LoginRequiredMixin, ListView):
    model = CartItem
    template_name = 'catalog/cart.html'

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['total_price'] = sum(
            item.product.price * item.quantity for item in context_data['cartitem_list'])
        return context_data


class AddToCartView(LoginRequiredMixin, DetailView):
    model = Product

    def get(self, request, *args, **kwargs):
        product = self.get_object()
        cart_item, created = CartItem.objects.get_or_create(
            product=product, user=request.user)
        cart_item.quantity += 1
        cart_item.save()
        return redirect(self.request.GET.get('next', reverse('catalog:index')))


class RemoveFromCartView(LoginRequiredMixin, DeleteView):
    model = CartItem
    success_url = reverse_lazy('catalog:view_cart')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{{ title }}</title>
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/bootstrap-formhelpers.min.css' %}" rel="stylesheet" media="screen">
</head>
{% include 'catalog/includes/inc_title.html' %}

<body>
	<div class="container">



		{% block content %}
		{% endblock %}
		<footer class="pt-4 my-md-5 pt-md-5 border-top">
			<div class="container">
				<div class="row">
					<div class="col-12 col-md">
						<img class="logo" src="/media/products/my-Softy (1).png" />
						<small class="d-block mb-3 text-muted">&copy; 2023</small>
					</div>
					<div class="col-6 col-md">
						<h5>Категории</h5>
						<ul class="list-unstyled text-small">
							<li><a class="text-muted" href="/category/1">Стулья</a></li>
							<li><a class="text-muted" href="/category/2">Столы</a></li>
							<li><a class="text-muted" href="/category/3">Диваны</a></li>
							<li><a class="text-muted" href="/category/4">Шкафы</a></li>
						</ul>
					</div>
					<div class="col-6 col-md">
						<h5>Дополнительно</h5>
						<ul class="list-unstyled text-small">
							<li><a class="text-muted" href="/news/">Мы пишем</a></li>
						</ul>
					</div>
					<div class="col-6 col-md">
						<h5>О нас</h5>
						<ul class="list-unstyled text-small">
							<li><a class="text-muted" href="/contacts/">Контакты</a></li>
						</ul>
					</div>
				</div>
			</div>
		</footer>
	</div>
	<script src="{% static 'js/bootstrap-formhelpers.min.js' %}"></script>
	<script src="{% static 'js/jquery.min.js'  %}"></script>
	<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

catalog/templates/catalog/cart.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container">
	<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
		<h1 class="display-4">Корзина</h1>
	</div>
	{% if object_list %}
	<div class="list-group">
		{% for object in object_list %}
		<div class="list-group-item d-flex justify-content-between">
			<div>
				<h4 class="list-group-item-heading">{{ object.product.name }}</h4>
				<p class="list-group-item-text">Цена: {{ object.product.price }}$ x{{object.quantity}}</p>
			</div>
			<div class="d-flex align-items-center">
				<a href="{% url 'catalog:remove_from_cart' object.id %}" class="btn btn-sm btn-danger">Удалить</a>
			</div>
		</div>
		{% endfor %}
		<div class="list-group-item active d-flex justify-content-between">
			<div>
				<h4 class="list-group-item-heading">Итого: {{ total_price }}$</h4>
			</div>
			<div class="column d-flex align-items-center">
				<a href="{% url 'orders:create' %}" class="btn btn-sm btn-dark">Оформить</a>
			</div>
		</div>
		{% else %}
		<h3>В корзине ничего нет</h3>
		{% endif %}
	</div>
</div>
{% endblock %}

catalog/templates/catalog/category_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<h1 class="display-4">{{ title }}</h1>
</div>

<div class="row row-cols-1 row-cols-md-2 row-cols-sm-2 g-4 text-center">
	{% for object in object_list %}
	{% if object.is_published %}
	<div class="col-lg-4 col-md-6 col-sm-6">
		<div class="card h-100">
			<div class="text-center">
				<img class="m-3" style="object-fit:cover; width: 200px; height: 200px;"
					src="{% mediapath object.image %}" />
			</div>
			<div class="card-body">
				<h3 class="card-title pricing-card-title">{{ object }}</h3>
				<ul class="list-unstyled mt-3 mb-4 text-start m-3">
					<p>{{ object.category }}</p>
					<p>{{ object.description|truncatechars:100 }}</p>
				</ul>
			</div>
			<div class="p-3">
				<a href="{% url 'catalog:view' object.pk %}" type="button"
					class="btn btn-lg btn-primary btn-block btn-outline-dark mt-auto">Подробнее</a>
				<a href="{% url 'catalog:add_to_cart' object.pk %}" type="button"
					class="btn btn-lg btn-info btn-block btn-outline-primary">Добавить в корзину</a>
				{% if perms.catalog.change_public %}
				<a href="{% url 'catalog:public_product' object.pk %}" type="button"
					class="btn btn-lg btn-danger btn-block btn-outline-danger">Снять с публикации</a>
				{% endif %}
			</div>
		</div>
	</div>
	{% endif %}
	{% endfor %}
	{% if request.user|has_group:1 or user.is_superuser%}
	{% for object in object_list %}
	{% if not object.is_published %}
	<div class="col-lg-4">
		<div class="card h-100">
			<div class="text-center">
				<img class="m-3" style="object-fit:cover; width: 200px; height: 200px;"
					src="{% mediapath object.image %}" />
			</div>
			<div class="card-body">
				<h3 class="card-title pricing-card-title">{{ object }}</h3>
				<ul class="list-unstyled mt-3 mb-4 text-start m-3">
					<p>{{ object.category }}</p>
					<p>{{ object.description|truncatechars:100 }}</p>
				</ul>
			</div>
			<div class="p-3">
				<a href="{% url 'catalog:view' object.pk %}" type="button"
					class="btn btn-lg btn-primary btn-block btn-outline-dark mt-auto">Подробнее</a>
				{% if perms.catalog.change_public %}
				<a href="{% url 'catalog:public_product' object.pk %}" type="button"
					class="btn btn-lg btn-danger btn-block btn-outline-danger">Снять с публикации</a>
				{% endif %}
			</div>
		</div>
	</div>
	{% endif %}
	{% endfor %}
	{% endif %}
</div>
{% endblock %}

catalog/templates/catalog/category_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">
                Добавление категории
        </h1>
    </div>

    <div class="col-12">
        <form class="row" method="post">
            {% csrf_token %}
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                            {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                                Создать
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<h1 class="display-4">Категории</h1>
</div>

{% if user.is_staff %}
<div class="col-12 mb-5">
	<a href="{% url 'catalog:category_create' %}" class="btn btn-sm btn-outline-primary">Добавить категорию</a>
</div>
{% endif %}
<div class="row row-cols-1 row-cols-md-2 row-cols-sm-2 g-4 text-center">
	{% for object in object_list %}
	<div class="col-lg-4 col-md-6 col-sm-6">
		<div class="card h-100">
			<div class="card-body d-flex flex-column">
				<h3 class="card-title pricing-card-title">{{ object }}</h3>
				<ul class="list-unstyled mt-3 mb-4 text-start m-3">
					<p>{{ object.description|truncatechars:100 }}</p>
				</ul>
			</div>
			<div class="p-3">
				<a href="{% url 'catalog:category_products' object.pk %}" type="button"
					class="btn btn-lg btn-primary btn-block btn-outline-dark mt-auto">Подробнее</a>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<h1 class="display-4">Контакты</h1>
</div>

<div class="row text-start">
	<div class="col-lg-9 col-md-6 col-sm-12">
		<div class="card mb-4 box-shadow">
			<div class="card-body">
				<table class="table table-striped">
					<tr>
						<td class="w-25">Страна</td>
						<td>Россия</td>
					</tr>
					<tr>
						<td class="w-25">ИНН</td>
						<td>000123123123</td>
					</tr>
					<tr>
						<td class="w-25">Адрес</td>
						<td>г.Москва, ул.Примерная, д1к1</td>
					</tr>
					<tr>
						<td class="w-25">Телефон</td>
						<td>+7 (495) 123-45-67</td>
					</tr>
					<tr>
						<td class="w-25">Email</td>
						<td>info@example.com</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
	<div class="col-lg-3 col-md-6 col-sm-12">
		<div class="card mb-4 box-shadow">
			<div class="card-header">
				<h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
			</div>
			<div class="card-body">
				<form method="post" action="" class="form-floating">
					{% csrf_token %}
					<div class="mb-3">
						<label for="name">Имя</label>
						<input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
					</div>
					<div class="mb-3">
						<label for="phone">Телефон</label>
						<input type="text" name="phone" class="form-control" id="phone" placeholder="Ваш телефон"
							required>
					</div>
					<div class="mb-3">
						<label for="email">Электронная почта</label>
						<input type="email" name="email" class="form-control" id="email" placeholder="Ваша почта"
							required>
					</div>
					<div class="mb-3">
						<label for="message">Сообщение</label>
						<textarea type="text" name="message" class="form-control" id="message" placeholder="Текст"
							required></textarea>
					</div>
					<button type="submit" name="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить
					</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}


<div class="pricing-header px-3 py-1 pt-md-1 pb-md-4 mx-auto text-center">
	<img class="logo" src="/media/products/my-Softy (2).png" />
	<h2>We help make your home really comfy</h2>
</div>

{% if user.is_staff %}
<div class="col-12 mb-5">
	<a href="{% url 'catalog:create' %}" class="btn btn-sm btn-outline-primary">Добавить товар</a>
</div>
{% endif %}
<div class="row row-cols-1 row-cols-md-2 row-cols-sm-2 g-4 text-center">
	{% for object in object_list %}
	{% if object.is_published %}
	<div class="col-lg-4 col-md-6 col-sm-6">
		<div class="card h-100">
			<div class="text-center">
				<img class="m-3" style="object-fit:cover; width: 200px; height: 200px;"
					src="{% mediapath object.image %}" />
			</div>
			<div class="card-body">
				<h3 class="card-title pricing-card-title">{{ object }}</h3>
				<ul class="list-unstyled mt-3 mb-4 text-start m-3">
					<p>{{ object.category }}</p>
					<p>{{ object.description|truncatechars:100 }}</p>
				</ul>
			</div>
			<div class="p-3">
				<a href="{% url 'catalog:view' object.pk %}" type="button"
					class="btn btn-lg btn-primary btn-block btn-outline-dark mt-auto">Подробнее</a>
				<a href="{% url 'catalog:add_to_cart' object.pk %}" type="button"
					class="btn btn-lg btn-info btn-block btn-outline-primary">В корзину</a>
				{% if perms.catalog.change_public %}
				<a href="{% url 'catalog:public_product' object.pk %}" type="button"
					class="btn btn-lg btn-danger btn-block btn-outline-danger">Снять с публикации</a>
				{% endif %}
			</div>
		</div>
	</div>
	{% endif %}
	{% endfor %}
	{% if request.user|has_group:1 or user.is_superuser%}
	{% for object in object_list %}
	{% if not object.is_published %}
	<div class="col-lg-4 col-md-6 col-sm-6 text-muted">
		<div class="card h-100">
			<div class="text-center">
				<img class="m-3" style="object-fit:cover; width: 200px; height: 200px;"
					src="{% mediapath object.image %}" />
			</div>
			<div class="card-body">
				<h3 class="card-title pricing-card-title">{{ object }}</h3>
				<ul class="list-unstyled mt-3 mb-4 text-start m-3">
					<p>{{ object.category }}</p>
					<p>{{ object.description|truncatechars:100 }}</p>
				</ul>
			</div>
			<div class="p-3">
				<a href="{% url 'catalog:view' object.pk %}" type="button"
					class="btn btn-lg btn-primary btn-block btn-outline-dark mt-auto">Подробнее</a>
				{% if perms.catalog.change_public %}
				<a href="{% url 'catalog:public_product' object.pk %}" type="button"
					class="btn btn-lg btn-block btn-outline-primary">Опубликовать</a>
				{% endif %}
			</div>
		</div>
	</div>
	{% endif %}
	{% endfor %}
	{% endif %}
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}


{% block content %}

<div class="col-12 px-3 py-3 pt-md-5 pb-md-4 mx-auto ">
	<div class="row text-start">
		<div class="col-4">
			<img style='height: 100%; width: 100%; object-fit: contain' src="{{ object.image|mediapath }}" />
		</div>
		<div class="col-8">
			<div class="card mb-4 box-shadow">
				<div class="card-header">
					<h3 class="card-title">
						{{ object.name }}
					</h3>
				</div>
				<div class="card-body">
					<p>
						Описание: {{ object.description }}
					</p>
					<p>
						Категория: {{ object.category }}
					</p>
					<p>
						Цена: {{ object.price }} $
					</p>
					<p>
						Дата изменения: {{ object.data_changed }}
					</p>
					<div class="d-flex justify-content-between align-items-center">
						<div class="btn-group">
							<a href="{% url 'catalog:add_to_cart' object.pk %}"
								class="btn btn-sm btn-outline-dark">Добавить в
								корзину</a>
							{% if request.user == object.owner or request.user.is_superuser%}
							<a href="{% url 'catalog:edit' object.pk %}" class="btn btn-sm btn-outline-primary">Edit</a>
							<a href="{% url 'catalog:delete' object.pk %}"
								class="btn btn-sm btn-outline-danger">Delete</a>
							{% elif request.user|has_group:1 %}
							<a href="{% url 'catalog:edit' object.pk %}" class="btn btn-sm btn-outline-primary">Edit</a>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}